apiVersion: networking.k8s.io/v1 # Kubernetes API version for networking resources
kind: Ingress # Resource type: manages external access to services
metadata:
  name: express-app-ingress # Ingress name for identification
  namespace: express-mongo-app # Namespace where ingress runs
  annotations: # Ingress controller specific configurations
    nginx.ingress.kubernetes.io/rewrite-target: / # Rewrite URL paths to root
    nginx.ingress.kubernetes.io/ssl-redirect: "false" # Disable SSL redirect
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false" # Don't force HTTPS
    nginx.ingress.kubernetes.io/rate-limit: "100" # Limit to 100 requests per window
    nginx.ingress.kubernetes.io/rate-limit-window: "1m" # Rate limit window: 1 minute
spec:
  ingressClassName: nginx # Use NGINX ingress controller
  rules: # Traffic routing rules
    - http: # HTTP traffic configuration (no specific host - works with any cluster)
        paths: # URL path routing rules
          - path: / # Root path
            pathType: Prefix # Match paths starting with /
            backend: # Backend service configuration
              service: # Service backend type
                name: express-app-service # Service name to route to
                port: # Service port configuration
                  number: 80 # Port number on the service
          - path: /api # API path
            pathType: Prefix # Match paths starting with /api
            backend: # Backend service configuration
              service: # Service backend type
                name: express-app-service # Same service for API routes
                port: # Service port configuration
                  number: 80 # Port number on the service
          - path: /mongo # MongoDB demo path
            pathType: Prefix # Match paths starting with /mongo
            backend: # Backend service configuration
              service: # Service backend type
                name: express-app-service # Same service for MongoDB routes
                port: # Service port configuration
                  number: 80 # Port number on the service
