apiVersion: v1 # Kubernetes API version for core resources
kind: ConfigMap # Resource type: stores configuration data as key-value pairs
metadata:
  name: express-app-config # ConfigMap name for referencing in deployments
  namespace: express-mongo-app # Namespace where this ConfigMap lives
data: # Configuration data section
  NODE_ENV: "production" # Environment variable for Node.js application
  APP_NAME: "Express.js + MongoDB on Minikube" # Application name for display purposes
  # MongoDB connection configuration
  MONGO_HOST: "mongo-service" # MongoDB service name for internal communication
  MONGO_PORT: "27017" # MongoDB default port
  MONGO_DATABASE: "express_app" # Database name for the application
  MONGO_AUTH_SOURCE: "admin" # Authentication database
